### ISSUE TITLE
Improve the way to see who reacted to you

### ISSUE THREAD

**Issue by zvirja** [k0shk0sh/FastHub#1007]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Tab S2 8.0  
---

GitHub and app allow to leave a reaction on a particular comment. App displays those reactions, however no way to see who exactly left them. In GitHub you can long tap or hover the mouse to see nicknames. Could you please add something similar to the app?

Thanks!

**Comment by k0shk0sh** [comment]
you can do that 😏. could u try it before opening?

**Comment by zvirja** [comment]
Yep, I tired to long tap on your thumb up, but nothing happened. Could you clarify how exactly  I should tap to see who liked my comment above?

**Comment by zvirja** [comment]
OK, I need to expand the list and tap there - now I see.

That is not very intuitive. Could you show this pop up when I tap on the emoji icon at the bottom of the comment?

**Comment by yakov116** [comment]
@zvirja agree!

**Comment by k0shk0sh** [comment]
the bottom icons are just one textview that shows the whole emojies in one, so we can't have them each clicked and I'm not gonna duplicate the images so each could do the same,  so sorry, this is gonna remain as it is for now until actually I find a better design for the whole list.

P.S: I couldn't make a new release because I don't have internet connection, waiting for the technical guy to install the internet and hopefully its done tomorrow or after.

**Comment by zvirja** [comment]
It still isn't clear to me, why you cannot have N textviews in a row, instead if having a single large one. Each textview will have the `OnLongPress` handler showing the pop-up. You will not need to store icons as render mechanism would be exactly the same as for single textview.

Hope that makes sense..

**Comment by zvirja** [comment]
@k0shk0sh Could you elaborate? It would be a really cool feature if only possible to implement it.. The current approach is really clumsy :persevere:

**Comment by TheSharpieOne** [comment]
I agree, this is not very intuitive. I was going to create an issue about not being able to view who reacted but I found this because I searched first :smile: but even after the original reply saying the app already does it, it wasn't immediately obvious how to do it within the app. (I see it now, but again, not very intuitive.)

**Comment by zvirja** [comment]
Yes. That's why I would ask @k0shk0sh to change the behavior if possible. It would be the really cool feature. Also that will allow to avoid extra-clicks - everyone would be happy 😄

**Comment by TheSharpieOne** [comment]
Yes, I expect it to work as you describe. As it currently is, it breaks the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
