### ISSUE TITLE
Reduce tab

### ISSUE THREAD

**Issue by giosil** [k0shk0sh/FastHub#1027]
**FastHub Version: 4.3.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HUAWEI  
- **Model:** HUAWEI P9 lite  
---

Tab size is too long...

**Comment by k0shk0sh** [comment]
could you please be more specific in what you referring to?

where, what and why? I can't figure out everything myself.

**Comment by giosil** [comment]
in the source code display the "tab" is represented by 8 characters. in the
smartphone this is uncomfortable would be better 4 or configurable. It's a
small improvement, great app anyway. Thank you.

Il 28 set 2017 9:35 PM, "Kosh Sergani" <notifications@github.com> ha
scritto:

**Comment by k0shk0sh** [comment]
thanks for your feedback, but this isn't something that could change, basically cropping the string will take away their meaning, that's why the tabs are scrollable. 

thanks again.

**Comment by JobLeonard** [comment]
@k0skhk0sh: I think something got lost in translation.

Setting the tab indentation size has nothing to do with cropping the string. It is about how many spaces each `\t` character is printed as. In most browsers and editors, this defaults to 8 spaces. These days, many developers prefer 2 or 4 (personally, I prefer 3 but I don't know anyone else who does that). 

Since fasthub code themes are CSS based, I assume it uses Android WebView. That should mean the number of spaces in the indentation can be changed via `tab-width` in the CSS for the code viewer. See https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size
