### ISSUE TITLE
Support for embedded code snippets.

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#1033]
**FastHub Version: 4.3.0**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** Yota Devices Limited  
- **Brand:** YotaPhone  
- **Model:** YotaPhone2  
---  
https://github.com/blog/2415-introducing-embedded-code-snippets  
Currently embeded code snippets are displayed incorrectly.

Browser:  
![screenshot_20170930-003024_1024](https://user-images.githubusercontent.com/1936922/31037248-b0a7b5b8-a578-11e7-9427-42b04ee7ffde.png)

FastHub:  
![screenshot_20170930-003058](https://user-images.githubusercontent.com/1936922/31037323-09c0d288-a579-11e7-9c25-cd6bcde5b9b4.png)

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/blob/a8ea45b330a03a59de84e52499d44c5b9aa5f1dd/app/src/main/java/com/fastaccess/ui/modules/main/MainActivity.java#L8

Test!!!

**Comment by k0shk0sh** [comment]
Its hard to that as each element in the code is generated separately in code :'(

**Comment by zvirja** [comment]
Just to clarify - so what is the plan? Do we simply keep it as is or you will fix it somehow (e.g. completely remove)?

**Comment by k0shk0sh** [comment]
@zvirja not sure what other clarification you need? My answer was clear.

**Comment by zvirja** [comment]
Probably that is not so obvious given that I decided to clarify 😞 

You haven't described the plan and simply closed the issue. The way "keep that as is" doesn't look fine because the rendered content is a garbage and is totally unreadable. I believe that you should to change it somehow. If you cannot support the feature, simply don't render it at all. That will be much better solution that current trash.

**Comment by k0shk0sh** [comment]
You always assume that things are easy to fix. I have said that each element is rendered separately and therefore I can't hold the whole part of this response in my hand.

Also, please could you look at the response before judging?

**Comment by zvirja** [comment]
> You always assume that things are easy to fix.

Nope, I don't. However I don't agree with the approach to simply close such issues.

Usually it's expected that maintainer _accepts_ the issue if that is a bug. It might be not fixed for some time, but at least it should be opened so you and other clients see that such issue is indeed present. Later maintainer could see that there is a huge number of issues in the particular area, so he could decide to e.g. redesign the approach to fix all the similar issues. I believe that we shouldn't simply close such bugs because you don't have time for them for now.

If issue is closed - there is no chance to see that the error exists.

I'm also a maintainer of OSS projects and we also have issues which are difficult to fix. However, they are always kept open and are never closed with "it's hard to fix - won't fix that OutOfMemoryException". I'm a bit frustrated by the behavior I see here, so that might be a reason why my replies look strange to you.

> Also, please could you look at the response before judging?

Be sure, I read it 😉

**Comment by k0shk0sh** [comment]
I did tried to fix it and I didn't close the issue until I made sure its gonna be to complicated to fix. 

If you see response

Div > link > table and whatsoon

**Comment by ishitatsuyuki** [comment]
Complicated != Impossible; do not close issue just because you can't tackle, it will attract more duplicates. This is a valid feature request. If you are not going to implement this, how about reopen and label "help wanted"?

**Comment by yakov116** [comment]
@ishitatsuyuki yes sir!!!!!

Would you like to send a pr??
