### ISSUE TITLE
Back button inconsistency

### ISSUE THREAD

**Issue by pekosoG** [k0shk0sh/FastHub#1073]
**FastHub Version: 4.4.1**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G(4) Plus  
---

#### The behavior of the back button differs from one screen to another.

For example, if you go to: 

1. trending list
2. select a repo
3. then click on the top left back button you got redirected to the news feed screen

 **but** if you do the same with:

1. gist list
2. select a gist
3. the click the same back button, you got back to the gist lists instead the news feed.

According to my judgement, you should go back to the screen that bring you wherever you are, so trending should perform the same behavior and go back to the trending list.

_Sent from my Moto G(4) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Hey, as explained in the other issue, it works as intended, that's why it's called home up, for gists I see that it's valid to go back to the list because that's the start point for gists, but I think it won't work if its a deep link, that's why I asked you to open this issue :) . 


always use home back button to navigate back to where you were, click upper button if you want to navigate in the context of whatever is on the screen.
