### ISSUE TITLE
Scroll lag when dragged from code fields

### ISSUE THREAD

**Issue by samdenty99** [k0shk0sh/FastHub#1082]
**FastHub Version: 4.4.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** Motorola  
- **Brand:** Motorola  
- **Model:** Moto G4  
---

How to reproduce:

- Open a large README file
- Scroll down to a code field
- Scroll up and down using the code field as the anchor point

Expected result:

- Scrolling should be as smooth as when the code field isn't used as an anchor point

Actual result:

- Scrolling lags 60-75% of the frames

**Comment by k0shk0sh** [comment]
can you attach video?

**Comment by samdenty99** [comment]
It's not as visible in this GIF as it is on device but here it is ![https://media.giphy.com/media/xT9IgxUQJvL1FTMF7q/giphy.gif](https://media.giphy.com/media/xT9IgxUQJvL1FTMF7q/giphy.gif)

**Comment by k0shk0sh** [comment]
Thanks for gif, it helped alot to explain the issue. 

I have commented on few similar issues (where there is a bit of lag on large files) well honestly I can't do much about it because its Android WebView limitation and your device capabilities :D.. 

P.S: once you touch a code or table (that is scrollable horizontally) you wont be able to scroll up or down until you touch outside it.
