### ISSUE TITLE
No feed from watched/pinned repositories

### ISSUE THREAD

**Issue by floreks** [k0shk0sh/FastHub#1137]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G6  
---

I have noticed some time ago that main feeds view does not contain information from my watched/pinned repositories anymore. I'm sure that it worked before and I was able to see feeds about newly created issues/PRs etc.

**Comment by yakov116** [comment]
@floreks Stupid github! They changed the api,

**Comment by k0shk0sh** [comment]
I'm curious as well as you are, it's GitHub that dropped these events even in their website feeds.

I really would appreciate if someone could contact them and ask them why they did such change.

**Comment by yakov116** [comment]
https://twitter.com/GitHubHelp/status/919280312261206017

**Comment by floreks** [comment]
Ahh... that's too bad :/ I hope they will bring it back. Thanks for explanation.

**Comment by yakov116** [comment]
@k0shk0sh great news

Hi Yakov -- thanks for reaching out about this.

The changes made to the API were not intentional, and it's possible they happened due to the changes made to the web UI's news feed recently (those changes to the UI's news feed were intentional and a part of an effort to improve the dashboard and news feed). The team is looking into why this happened in the API and into fixing this, but it doesn't seem to be a trivial problem. We have an issue open internally for this and a link to your message so we'll be able to followup with you as soon as there's any news here. We're sorry for the trouble, and wanted to thank you again for reporting this.

Best,
Ivan

**Comment by k0shk0sh** [comment]
Another five years to get this fixed 😂

**Comment by floreks** [comment]
I think they have brought it back finally! yay :)
