### ISSUE TITLE
Switch branch and tabs

### ISSUE THREAD

**Issue by umbe1987** [k0shk0sh/FastHub#1162]
**FastHub Version: 4.4.2**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** Huawei  
- **Model:** P8 Lite  
---
Hi. This is just an opinion of my first minute use of the app. When one switches branch in (e.g.) code tab of a repo, and then goes to commit tab, the branch should remain the same, not the ome before the change.
Example: I switch from master to dev branch under code tab, I go to commit tab because I'd like to see dev branch commits, but it still shows master ones and I need to check out branch again.
Anyway, thanks for the beautiful app!

**Comment by k0shk0sh** [comment]
Hey thanks for your input,

That's more like an opinionated solution, I'd rather to keep this way and let use choose instead of me making another API request the user might not be interested on.  

Also you can long click on file or directly to see its changes within the branch you selected without going to commit tab ;)
