### ISSUE TITLE
Pressing back button inside the directory of any repository makes you jump back TWO directories at once under given conditions-

### ISSUE THREAD

**Issue by Gauti4417** [k0shk0sh/FastHub#1167]
**FastHub Version: 4.4.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** Moto G (5) Plus  
---

**Problem I faced(bug)-**
Whenever i was in third directory(taking root directory to be zero) of any repository, pressing the back button resulted in jumping back to the first directory, i.e., it skipped 2nd directory.

You might not understand it clearly like this, so I have attached two images to make sure you get what I am saying.!

![Before Pressing back button in the third directory](https://i.imgur.com/nVMJHOW.png)

![After pressing back button in the third directory](https://i.imgur.com/ihHjpJX.jpg)

**Comment by cozyplanes** [comment]
Duplicate1124

**Comment by yakov116** [comment]
@cozyplanes nope I think this is diff

**Comment by cozyplanes** [comment]
@yakov116 oops, linked the wrong one
I talked about this issue before with kosh, but he said it is intended, and he won't fix it

**Comment by yakov116** [comment]
@cozyplanes this issue I have never seen before. Pressing the back button will work for all submenus except step 3? Can you point me to the issue?

**Comment by k0shk0sh** [comment]
Search before opening new issue, there is no reward on who open the most issues!!!

**Comment by Gauti4417** [comment]
@k0shk0sh  wow! you are so arrogant man. i was just trying to help here. and it's not my job to search between thousand of issues before reporting, because i am the user of this app. you being the developer has to accept the fact that there might b multiple issues of same type.

and that's the kind of reply i get after trying to do some good here.

**Comment by k0shk0sh** [comment]
Calm down!!.

First of all you should search because it's written everywhere that you should search first. 

Being the dev doesn't mean that the users "as you said" don't help to eliminate such waste of time discussion and waste of time for the OP to put an effort on something that is duplicated and will be closed immediately once its duplicated as mentioned in the faq. These are the rules and you should follow.

Now back to me being arrogant,  well, thanks.

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/2L85ANc.png)

**Comment by Gauti4417** [comment]
okay then tell me which open issue this one was....i have read all the opened issue and none of them point to this one...

look mate, i have no problem if you duplicate my issue or close it or anything... but that 'reward' thing you said was quite harsh...i am not doing this for any kind of reward or something...i just thought i should report something that was not in the opened section...

and i am calm.!!!

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/issues/939

**Comment by Gauti4417** [comment]
it's closed...

**Comment by cozyplanes-development** [comment]
@Gauti4417 ok, so lets clarify this
The issue being closed means it is invalid, finished, or wont fix
The  #939 issue is the issue reported before
which makes your issue  duplicate
and you should search if the issue was in the closed section. 
I know that your guess should be in the opened section because it isn't fixed, but remember
there are some issues that the dev wont fix
or the issue you mentioned is working as the dev intended to.

So,
- search throughly
- dont be harsh to the devs, they work hard to make wonderful experience to the users, but they cant stay calm if you dont be patient or nice to them

Thank you, and have a nice day using FastHub.

**Comment by Gauti4417** [comment]
Yeah you are right.... I apologise @k0shk0sh... My bad...

**Comment by cozyplanes-development** [comment]
There wont be any problems.
Have a nice day.
On 2017 M10 22, at 10:20 PM, Gautam Rajeev Singh <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah you are right.... I apologise @k0shk0sh<https://github.com/k0shk0sh>... My bad...
