### ISSUE TITLE
Cannot authorise app

### ISSUE THREAD

**Issue by mindbound** [k0shk0sh/FastHub#127]
After installing the Google Play version and logging in, I cannot finish the authentication, as the "Authorize application" button is disabled (visible but untouchable). The problem persists with reinstalling the app.

Android 6.0.1, Galaxy Tab A SM-T550.

**Comment by k0shk0sh** [comment]
Its strange, can you login from ur desktop and see the authorized apps? maybe github has limit of authorizing apps or something. try and delete one or if you find FastHub try and remove it and try again. let me know how this goes with you because im planning to make a release later today.

**Comment by mindbound** [comment]
I revoked access from 3 of my 11 authorised apps, reinstalled FastHub, and observed no change.

**Comment by k0shk0sh** [comment]
@mindbound that's pretty sure strange, I will have a look after I back home and buzz you on this once I could produce and fix it. thanks for your patience.

**Comment by k0shk0sh** [comment]
@mindbound I'm abit lost here, but here is what I could think of, is your account tied to an organization? maybe one of the permissions is to delete a repo which I removed it in my last commit, I'm also now trying to implement basic auth instead of using github website and parse the login.

I hope when I release 1.1.0 you won't have problems afterward.

**Comment by mindbound** [comment]
My account isn't tied to any organisation, so that shouldn't be the cause of this issue. I'll wait for the new version to come out, let's see if that fixes this.

**Comment by mindbound** [comment]
The new login system fixed the problem, thank you.
