### ISSUE TITLE
Allow to pin searches

### ISSUE THREAD

**Issue by retog** [k0shk0sh/FastHub#1371]
**sabes Version: 4.6.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** samsung  
- **Brand:** samsung  
- **Model:** Galaxy Note8  
---

Having a way to bookmark a search would be incredibly useful, as it would allow for example to quickly access all issues meeting some relevance criteria.

**Comment by k0shk0sh** [comment]
The search terms are saved and you need to only enter first letter and there will be auto completion afterward to select what you typed previously.

Could you tell me usecase other than that? as I don't see the need to have pinning for searches if the search term is actually saved.

**Comment by retog** [comment]
There are categories of issues that I frequently want to access. For example I want to quickly find all issues assigned to me that have a certain label, e.g. is:open is:issue  label:"pending" assignee:"retog". On the desktop I use waffle.io but on the mobile I just would like to see the most important issues (the ones I'm working or should be working on next). The autocompletion is useful, but setting some pins on such complex queries would be even more.

Unfortunately opening FastHub with a github URI to the search (https://github.com/search?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue++label%3A%22pending%22+assignee%3A%22retog%22 for the example query doesn't give me the result, but a "Not Found" alert.

**Comment by k0shk0sh** [comment]
search uri isn't being handled by the app, but i'll do it right away :)

**Comment by k0shk0sh** [comment]
Now search urls should work, so the auto completion will do the trick for saving the search query.

**Comment by k0shk0sh** [comment]
Now search urls should work, so the auto completion will do the trick for saving the search query.

**Comment by jpschewe** [comment]
It would be nice to be able to pin searches. I like to search for open issues in a milestone. I tried putting text into the search box and wasn't prompted worth any auto completion. If I just had a ones search I could click on it from the side bar. It would also be nice to be able to name these pinned searches.

**Comment by Gorislim13** [comment]
Gorislim13

Or Alwaysredbull13@gmail.com 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 3/25/18, 6:49 PM Jon Schewe <notifications@github.com> wrote:
It would be nice to be able to pin searches. I like to search for open issues in a milestone. I tried putting text into the search box and wasn't prompted worth any auto completion. If I just had a ones search I could click on it from the side bar. It would also be nice to be able to name these pinned searches.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/k0shk0sh/FastHub","title":"k0shk0sh/FastHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/k0shk0sh/FastHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jpschewe in #1371: It would be nice to be able to pin searches. I like to search for open issues in a milestone. I tried putting text into the search box and wasn't prompted worth any auto completion. If I just had a ones search I could click on it from the side bar. It would also be nice to be able to name these pinned searches."}],"action":{"name":"View Issue","url":"https://github.com/k0shk0sh/FastHub/issues/1371#issuecomment-376024067"}}}
