### ISSUE TITLE
Format persists when pasting text in search field

### ISSUE THREAD

**Issue by gruhn** [k0shk0sh/FastHub#1393]
**FastHub Version: 4.6.0**  
**Android Version: 5.0.2 (SDK: 21)**  
**Device Information:**  
- **Manufacturer:** Lenovo  
- **Brand:** MEDION  
- **Model:** MEDION E4503  
---

When I copy words from a headline (or bold/italic text...) somewhere and paste them in the search field, the format persists. Not a big deal of course but I would intuitively expect search field content to be unformatted.

**Comment by k0shk0sh** [comment]
i'm not the one who is formatting the text, its rather an android framework that does that. you could check with any other apps and base on my experience they will behave the same. 
I don't think its a valid reason for me put effort into it because i'm not so sure how the fix will be. 

Thanks tho :) .

**Comment by gruhn** [comment]
Oh, sure. I assumed it's just a matter of switching a flag.

**Comment by k0shk0sh** [comment]
nope, not really :D .. i wish if it was :D

**Comment by k0shk0sh** [comment]
https://stackoverflow.com/questions/24758698/paste-without-rich-text-formatting-into-edittext/24777290
