### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by shinobisoft** [k0shk0sh/FastHub#1448]
**FastHub Version: 4.6.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG Stylo3  
---

How about adding an option in Settings to allow FastHub to start or open on a specific profile or anywhere else for that matter.

**Comment by yakov116** [comment]
@shinobisoft please search the issues. This has been asked many time. @k0shk0sh does not wish to implement

**Comment by yakov116** [comment]
@shinobisoft Each user has their own feelings. I understand your point of you view (pun intended), however the reason for being so quick to close the issue, is because you did not search before open this one. 
Side note: an "issue" is not necessarily an issue with the app, it mean that you opened a github issue. I hope you enjoy using the app!
