### ISSUE TITLE
Remove annoying loading dialogs

### ISSUE THREAD

**Issue by heinrichreimer** [k0shk0sh/FastHub#149]
Remove loading dialogs entirely and instead use things like `SwipeRefreshLayout` from the support library

**Comment by k0shk0sh** [comment]
Its necessary tho, even tho removing them is actually from one class, but we need to refactor other classes that actually has post methods in them to use progressDialog or at least show some sort of progress while blocking the submit button.

**Comment by k0shk0sh** [comment]
In 2.1.0 the dialog is still there however now its cancelable by clicking outside or back button.

**Comment by DreierF** [comment]
First of all thanks for the app and for putting so much of your time into it.
But regarding this issue: I don't really get how making the dialog cancelable solves the mentioned issue.
@heinrichreimer is totally right. Having a dialog, a progress bar and the pull-to-refresh indicator from the support library is really annoying. And always showing two of them at the same time unnecessary clutters the UI when switching screens. So I would definitely get rid of the progress dialog, disable the progress bar in the center when pull-to-refresh is triggered. When initially loading a page either the pull-to-refresh progress indicator (x)or the progress bar in the middle should be shown. Even better maybe with a delay so that you won't see the progress bar at all if your on a fast internet connection.

**Comment by k0shk0sh** [comment]
@DreierF I can't really get that you guys want to look at a screen that doesn't have anything without any progress indicator, for example: in Repo/Issue/PR/Commit screens, progress is a must otherwise you going to end up looking at a screen that don't have anything until there is something. 

I'm with not showing progressBar when refresh is showing, but progressDialog will remain for the screen mentioned above, otherwise there will be user who will just rate 1 star because they are looking at a screen that don't have anything for period of time which they will eventually  think that there is something wrong and retry again & there will be nothing to indicates that there is something is going on.

**Comment by heinrichreimer** [comment]
@DreierF I totally agree with you on that.
@k0shk0sh Solving this empty screen problem by using a loading dialog is the complete wrong way. Instead you should use a meaningful empty state layout. That can be some graphic or even just a short text to tell the user to hold on tight.

**Comment by heinrichreimer** [comment]
Take a look at the [guidelines](https://material.io/guidelines/patterns/empty-states.html#empty-states-avoiding-completely-empty-states).

**Comment by DreierF** [comment]
@k0shk0sh I didn't say there should be an empty screen. I just said it should be __one__  progress indicator. Not two of them or a dialog.
