### ISSUE TITLE
Minimizing app, then returning always sends you back to feed

### ISSUE THREAD

**Issue by ijacquez** [k0shk0sh/FastHub#1591]
**FastHub Version: 4.6.4**  
**Android Version: 6.0 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G4  
---

 If I minimize while in a repo, and I come back to the app, I get sent back to my feed.

**Comment by yakov116** [comment]
@ijacquez how did you open to the repo? Via a link or went to the app and went to repo?

**Comment by ijacquez** [comment]
I went to the app, clicked on my profile, went to my private repo, opened a file, then minimized.

**Comment by ijacquez** [comment]
This issue doesn't happen when I open the app the first time, go to "Issues", then minimize the app.

**Comment by xenreon** [comment]
You sure this isn't a problem with your phone's ram management? Making sure as not seeing anything as such at least with public repos.

**Comment by ijacquez** [comment]
It could definitely be. How would I verify that this is or isn't the case?

**Comment by k0shk0sh** [comment]
@xenreon that's true, his phone might decide to kill the activities that are running and therefore the app return to its initial state.

**Comment by ijacquez** [comment]
What is the other issue?

**Comment by yakov116** [comment]
@ijacquez #1479

This one for sure I'm certain there is more.

**Comment by Gorislim13** [comment]
Private keys I can't spend any coins error 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 3/20/18, 6:56 PM Israel Jacquez <notifications@github.com> wrote:
What is the other issue?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/k0shk0sh/FastHub","title":"k0shk0sh/FastHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/k0shk0sh/FastHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ijacquez in #1591: What is the other issue?"}],"action":{"name":"View Issue","url":"https://github.com/k0shk0sh/FastHub/issues/1591#issuecomment-374814450"}}}

**Comment by Gorislim13** [comment]
Set up private keys I will pay u 3 btc 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 3/20/18, 6:56 PM Israel Jacquez <notifications@github.com> wrote:
What is the other issue?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/k0shk0sh/FastHub","title":"k0shk0sh/FastHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/k0shk0sh/FastHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ijacquez in #1591: What is the other issue?"}],"action":{"name":"View Issue","url":"https://github.com/k0shk0sh/FastHub/issues/1591#issuecomment-374814450"}}}
