### ISSUE TITLE
Reading notifications

### ISSUE THREAD

**Issue by JonnyTech** [k0shk0sh/FastHub#17]
When clicking a notification it takes me to the repo rather than the issue. Am I missing something? (FastHub v1.0.3 from F-Droid)

**Comment by kylehendricks** [comment]
When I touch directly on a notification nothing is happening.  When I click the "OPEN" button on the notification, the app doesn't open and the notification drawer is dismissed.

**Comment by k0shk0sh** [comment]
Im aware of this issue and have did something about it yesterday night, you can check my commit for that. I will try and fix them asap.

**Comment by k0shk0sh** [comment]
Thanks guys for your feedback.

**Comment by k0shk0sh** [comment]
Sorry, when I replied, by that time, I just opened my eyes lol, to comment properly on the issue here is my revised comment: 

The problem with Github notification is that it does not tell you where the notification happened example on Issue or Pull Request, due to this, I'll have to find a workaround it and see what I could do about it. 

Currently in version 1.0.3 the notification open button does not work, but locally in my last changes it does, I'll just have to publish next release for it to work along with some bug fixes, I'll let you know when I do.!

**Comment by k0shk0sh** [comment]
Alright guys, This issue has been resolved and now notifications should be handled properly. will be out in release 1.0.4 later today.
