### ISSUE TITLE
Microsoft's pending purchase of GitHub and the future of FastHub

### ISSUE THREAD

**Issue by st42** [k0shk0sh/FastHub#1852]
With GitHub being purchased by Microsoft and thousands of users moving their projects to GitLab (myself included) are you considering adding GitLab compatibility or creating a secondary project solely for GitLab? People are leaving GitHub like rats fleeing a sinking ship. GitLab had a spike in traffic with 13,000 projects being imported within a single hour. People do not trust Microsoft and rightly so. Why would Microsoft pay $7.5 billion for GitHub (last valued at $2.5 billion) when GitHub's focus is on free and opensource software. I guess what I'm saying it might be prudent to consider GitHub's and FastHub's future.

**Comment by SuperSandro2000** [comment]
They paid way more for Minecraft than it is worth, too. They probably have a whole bunch of private repos that they could stop paying and maybe they move internal git structure to github or use it more extensive. Maybe they use Github Enterprise and save a bunch of bucks there. Anyway. Most bigger projects won't move anytime soon somewhere else because of CI and other integrated stuff. 
And about Gitlab: It would be a new app and not in the scope of fasthub.

**Comment by ryanmusante** [comment]
It would require a completely new app with a redesign based on gitlab. It would be a major undertaking.

**Comment by k0shk0sh** [comment]
I'm rewriting FastHub I might consider make it modular I'll see the effort to make that happen and if its applicable then I'll do it :l,

**Comment by cozyplanes** [comment]
Or make labcoat better again
Their ui is too hard to use

**Comment by lil5** [comment]
https://gitlab.com/Commit451/LabCoat
