### ISSUE TITLE
Releases tab

### ISSUE THREAD

**Issue by holykol** [k0shk0sh/FastHub#186]
How do you get the idea of ​​showing the 'releases' tab if they exist?

**Comment by kutsan** [comment]
Well, there is a releases tab under Code section. Is this what you asking for?
https://i.imgur.com/2Z4mBfw.png

**Comment by holykol** [comment]
I ask you to hide the tab when there are no releases. [Not everyone](https://imgur.com/gallery/K4j7x) uses this opportunity

**Comment by kutsan** [comment]
I am not sure whether it should be removed or not. In my opinion, it's a good indicator to say "There is no releases." instead of saying "Where the hell this releases section, even this app has one??". And even GitHub does this if repository don't have any release.

That error message indeed should be improved, though. No data available not that clear.

**Comment by kutsan** [comment]
Thanks for your suggestion. I am sorry but releases tab probably not going to removed. We need to get more UX-friendly decision. As I said, info message will be changed with more meaningful one.

I'm also going to close this issue. Feel free to open new one, any feedback highly appreciated.
