### ISSUE TITLE
Reactions don't stick

### ISSUE THREAD

**Issue by jsilvermist** [k0shk0sh/FastHub#1885]
**FastHub Version: 4.6.7**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

 If I leave a reaction, it looks like it works, until I exit and come back, or view it on the webpage, then my reaction is gone again.

**Comment by yakov116** [comment]
@jsilvermist link to the repo?

**Comment by jsilvermist** [comment]
I've noticed it across many different repos, so I don't think it's repo specific.

Have been online network-wise, and if you mean does it work on the webpage (github.com), then yes.

**Comment by yakov116** [comment]
@jsilvermist looks like your taking about a known issue

**Comment by jsilvermist** [comment]
Hmm looking at #524 I'm definitely experiencing that issue, but no matter how long I wait, the reaction is never added, so I think it's more than just the number being updated before the process is complete.

**Comment by yakov116** [comment]
@jsilvermist can you give a link to a post you tried?

**Comment by Idesmi** [comment]
This persists for me too.

**Comment by bender2k14** [comment]
I also have this problem.  I here are my steps.

1. Observe that the count of a particular reaction type for a particular comment is `n`
2. Leave that reaction on that comment
3. Observe that the count in question increases to `n+1`
4. Scroll to the top
5. Pull down to refresh the page
6. Return to observe the count in question

Expected behavior: The count is still `n+1`
Actual behavior: The count has returned to `n`

**Comment by yakov116** [comment]
This should be fixed update to the latest.

**Comment by TysonMN** [comment]
Indeed it is!  I gave that "hooray" reaction on your comment using the FastHub app.  Thank you very much.  This will save me lots of time :D

**Comment by jsilvermist** [comment]
My thumbs up stuck too, thanks!
