### ISSUE TITLE
Better notification support

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#199]
Notifications look like they're being posted as multiple notifications, so if I have a lot of them it locks up the system notification drawer for a few seconds. 

Group notifications or an inbox style would be better.

**Comment by kutsan** [comment]
I guess you haven't updated yet to [v1.4.0](https://github.com/k0shk0sh/FastHub/releases/tag/1.4.0). As you can see at #111.

**Comment by eygraber** [comment]
Are they being posted all at once, or in a batch? I have a few hundred unread notifications and when they get posted the notification drawer gets locked up.

**Comment by kutsan** [comment]
They are now posted in a batch. Like [this](https://i.imgur.com/3043hBz.png) and [this](https://i.imgur.com/tyLhvZ4.png). I hope this is what you are asking for?

**Comment by eygraber** [comment]
What I'm saying is that [here](https://github.com/k0shk0sh/FastHub/blob/7a1df22a0b739930012c146e9e582767c21d314d/app/src/main/java/com/fastaccess/provider/tasks/notification/NotificationSchedulerJobTask.java#L120) each unread notification is posted as a `Notification` but if there are a lot of them, it will lock up the notification drawer. There should be some way to post them all at once, or stagger them so it doesn't lock up the UI.

**Comment by kutsan** [comment]
cc @k0shk0sh

**Comment by k0shk0sh** [comment]
I guess we should limit them to max 2 ? perhaps?

**Comment by kutsan** [comment]
Sorry for misunderstanding, re-opening. We should limit them at some point.

**Comment by k0shk0sh** [comment]
@eygraber could you let me know what is your current OS version? 
Because they are as @kutsan described, they are stacked as of Gmail style (Bundled together) as you see from [here](https://github.com/k0shk0sh/FastHub/blob/7a1df22a0b739930012c146e9e582767c21d314d/app/src/main/java/com/fastaccess/provider/tasks/notification/NotificationSchedulerJobTask.java#L110)

this notification is serving as a grouped (mother) notification that host all of the other notifications that are being showed in the link you provided.

**Comment by eygraber** [comment]
@k0shk0sh7.1.1 on a pixel

**Comment by k0shk0sh** [comment]
@eygraber I should have figured that out earlier as you are suffering the nightmode, which I just tested it out in 6.0.1 and it look amazing 😌😌. 
alright then, I guess a limit to the notification should do. 
thanks.
