### ISSUE TITLE
Notifications Don't Work

### ISSUE THREAD

**Issue by Ephellon** [k0shk0sh/FastHub#2123]
**FastHub Version: 4.6.7**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG Premier Pro  
---

When I'm supposed to receive a notification (new message, pull request, etc.) nothing happens within or outside the application.

**Comment by k0shk0sh** [comment]
Click settings/notifications/interval and select ur choice.


Please also search the issues before submitting new one. 

Thanks

**Comment by Ephellon** [comment]
Ha, I didn't get a notification for this. Also, I've had it set to 5 minutes since I installed it, and it says it's been 2H since you've closed this.

**Comment by k0shk0sh** [comment]
Did you search the issues in here? 



I'll just repeat myself:

Enable mail notifications from GitHub website. 

Your email notifications must be enabled in ur profile settings in order to receive new notifications. 



FastHub goes to GitHub notifications api every x you set. 

It has nothing to do with what you setup your profile with.

**Comment by Ephellon** [comment]
Disabled, re-enabled

**Comment by k0shk0sh** [comment]
Alright then, now on you shall receive notifications from FastHub as long as GitHub return some!.
