### ISSUE TITLE
README.rst files don't parse image links correctly. 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#223]
I've not really seen many which didn't use md, but a few days ago I came by a rst format. 

https://github.com/AmmsA/Githeat/blob/master/README.rst

And on the main repository view the image files aren't  read correctly.

https://github.com/AmmsA/Githeat

**Comment by k0shk0sh** [comment]
Yup, I'm aware of that, FastHub does an extra work to parse images and make sure they are displayed properly. Hence GitHub does not return absolute paths for images, FastHub will detect that in readme files (repo main readme) and try its best to construct links & images property. I'll see what I can do about the readme from the branch files, but can't promise much because the possibilities of links will be correct is low.

**Comment by GeorgeWL** [comment]
Yeah, it seems it's a common issue, I moved to FastHub once GitSkarios became a dropped project and they had the same issue, as did OctoDroid (which I uninstalled as it just felt very unpolished.)

rst files seem to be incredibly uncommon as readme though, so it's not exactly a priority.

**Comment by k0shk0sh** [comment]
To be fair to **FastHub** both mentioned apps, weren't as smart as FastHub in handling that, you could open the three apps, and check each app readme for instance, FastHub readme as it uses relative paths instead of absolute paths but yet FastHub does all it can do to parse relative links & images as you can see from this link [Class file](https://github.com/k0shk0sh/FastHub/blob/09e77bdab0ee3f641da5e5ea19d9ae5e6137b875/app/src/main/java/com/prettifier/pretty/helper/GithubHelper.java#L36-L36)

 I'll personally look more into the repo you mentioned above & see what I can do about it.

P.S: its not about file type, as i'm making sure to tell GitHub to give the file as an HTML format. so that shouldn't be a problem, the problem will always fall under the relative path :) .

**Comment by GeorgeWL** [comment]
aha, so I was thinking of the wrong cause, cool to know the real reason then :+1:

**Comment by k0shk0sh** [comment]
Alright, I got this working, I was doing it the wrong way tbh.
I was getting the readme files as `raw` instead of `html` which was the cause, the fix was to do something like [Method](https://github.com/k0shk0sh/FastHub/blob/ac55e1045c79bca7ad4e0d5460db423d03b9aa3c/app/src/main/java/com/fastaccess/provider/scheme/LinkParserHelper.java#L34-L34) convert the link to `api.github.com/repos/repo/contents/path` instead of `raw.githubconents.com` and then check if the file extension before calling the api to determine either to get it as a `raw` file or `html` .

**Comment by GeorgeWL** [comment]
Wizard
