### ISSUE TITLE
Sluggish when opening long files

### ISSUE THREAD

**Issue by vibhavsinha** [k0shk0sh/FastHub#2250]
**FastHub Version: 4.6.7**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** motorola  
- **Brand:** motorola  
- **Model:** motorola one power  
---

 Opening files of about 500 to 1000 lines results in the page scroll becoming very sluggish. Scrolling action takes about 2-5 seconds to complete.
This makes browsing code very difficult.
I don't know how else to describe this behaviour. Let me know if you need more information.

**Comment by k0shk0sh** [comment]
I'm aware of that and its different from one device to another and I can't promise i'll fix this in v5 the right way as its more like a device issue rather than the app issue, some devices ships an old version of the webview and therefore nothing much I can do!. i'll think of something later tho, meantime, this dup ;)
