### ISSUE TITLE
Gitea/Gogs support

### ISSUE THREAD

**Issue by Serkan-devel** [k0shk0sh/FastHub#2350]
Gitea is basically a lightweight Gitlab alternative but tries to replicate Github's APIs. Would be great to use self-hosted instances with this

**Comment by Serkan-devel** [comment]
why has this been closed?

**Comment by BytewaveMLP** [comment]
Although I don't like bumping issues from a year ago, it would be nice to at least get an explanation as to why this issue was closed with no comment. Gitea appears to provide a (mostly) compatible API, and it would be nice to see a well-developed app like FastHub support it. The only FOSS Gitea client I currently know of for Android is [GitNex](https://gitea.com/gitnex/GitNex), and it... leaves a lot to be desired compared to FastHub.
