### ISSUE TITLE
Download releases not working. 

### ISSUE THREAD

**Issue by HitaloKun** [k0shk0sh/FastHub#2838]
**FastHub Version: 4.6.9**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** Samsung
- **Brand:** Samsung
- **Model:** Galaxy J7 2016
---

When I try to download files in the "releases" tab i get a download failure notification.

_If this is a repeated issue, do you intend to fix this or is it not possible?_

**Comment by k0shk0sh** [comment]
Will be in next release.

**Comment by HitaloKun** [comment]
@k0shk0sh Thx bro, you're doing a great job! ^-^

**Comment by k0shk0sh** [comment]
Please update to 4.7.0

**Comment by HitaloKun** [comment]
@k0shk0sh Is it available now?

**Comment by k0shk0sh** [comment]
Yeah, for 50% of user base, if u r lucky u might be one of them, if not, I'll increase to 100% tomorrow morning

**Comment by HitaloKun** [comment]
@k0shk0sh I haven't received the update yet. 😅😂

**Comment by HitaloKun** [comment]
Done, updated with apk, lets test all.

**Comment by k0shk0sh** [comment]
Nice, please comment back when u try downloading :)

**Comment by HitaloKun** [comment]
@k0shk0sh Apparently it's not working yet, I tried to download the Source from FastHub in the releases tab.

**Comment by k0shk0sh** [comment]
Wait, the tar works but not the zip, the extension seems to be broken for I have no idea what reasons, maybe the url is not correct? 

Hmmm, I really thought that the issue referring to not being able to download at all because before this version downloading wasn't working.

U can for now, go to files tab and click on download icon urself until further release.

**Comment by k0shk0sh** [comment]
@HitaloKun just made a release fixing that issue and it will be available in an hour or minutes.
