### ISSUE TITLE
Bug | Missing settings shortcut in drawer

### ISSUE THREAD

**Issue by AndreaCioccarelli** [k0shk0sh/FastHub#307]
**App Version: 1.8.1
OS Version: 24
Model: samsung-SM-G950F**
Only the main activity have a shortcut to settings page, other pages (Such as Repository details) haven't "Action" items into the drawer. Generally drawer items shouldn't change between different activities because the user remember them as one single structure

**Comment by k0shk0sh** [comment]
It isn't a bug, due to some stuff that needs the app to be restarted it isn't there. I'll see what I can do about it

**Comment by k0shk0sh** [comment]
this commit af0074a actually closes this, however settings options isn't going to be in every screen due to the fact that it'll introduce another complexity where we have to recreate the whole back stack and there is no way but to restart the whole app so its going to remain as it until I actually do some sort of eventbus which I'm not planning to do :p
