### ISSUE TITLE
FastHub update notifications

### ISSUE THREAD

**Issue by darkwater** [k0shk0sh/FastHub#413]
**App Version: 1.9.5**

**OS Version: 25**

**Model: OnePlus-A0001**

Don't show them, especially when users use some sort of auto-updating. At the very least make them opt-in.

**Comment by k0shk0sh** [comment]
You could disable them from settings/ notification interval and choose turn off.

**Comment by k0shk0sh** [comment]
And please update to 2.0.1

**Comment by darkwater** [comment]
Wouldn't that also disable actual Github notifications? I don't see an option to only disable notifications from the app itself.  Also, if there were, having such an option on by default is bad user experience IMHO. I've known exactly one other app that does this, and I've uninstalled it because of it. I don't need these type of notifications since Google Play handles this automatically.

**Comment by k0shk0sh** [comment]
Owh, you are talking about the APP itself notifications, sorry I got this wrong, 

Well, that don't exists currently & if you think a notification to remind you to update the app every once awhile is bad then, i'll consider to remove it or provide an op-out option, yet, with the notification I still can see you are using an old version which you might be having some bugs that are fixed in newer version, which to be fair, anything that comes from <2.0.0 won't be taking serious and will be ignored (referring to bugs). 

I will provide an option for that. 

thanks

**Comment by k0shk0sh** [comment]
#405
