### ISSUE TITLE
Loading repository dialog is dismissable.

### ISSUE THREAD

**Issue by hassie-dash** [k0shk0sh/FastHub#471]
**App Version: 2.1.0**

**OS Version: 23**

**Model: LGE-Nexus 5**

Hey, great app. A potential bug maybe: I've noticed that the loading dialog which is shown after clicking on a repository is dismissable. After the dialog is dismissed, the repository loads instantly.

I believe that the dialog is not in sync with the repository load. Instead the repository starts to load after the dialog is automatically dismissed.

**Comment by JediBurrell** [comment]
Hey hassie, due to previous issues @k0shk0sh decided to make the dialog dismissable, this is on purpose.

As far as the delayed loading, the loader is for the repository information, and not the README page. The README page is loaded separately, and I'll see about possibly signifying that it's loading. Though it isn't a bug.

For now I'll close the issue, and I'll update this if a README loader is added.
Thank you for your submission!

**Comment by k0shk0sh** [comment]
As Jedi said, its on purpose, the dialog wasn't cancelable until last release. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hassie-dash** [comment]
Ok, cool :D. Thanks for the quick response.

**Comment by JediBurrell** [comment]
This issue has been partially appealed in 1af4696.
