### ISSUE TITLE
bug links in readme

### ISSUE THREAD

**Issue by Dreamersoul** [k0shk0sh/FastHub#49]
clicking on a link [non GitHub] in a readme file fails and tries to open it as a repo instead of opening it inside a webview

**Comment by k0shk0sh** [comment]
Im aware of that, I'm doing aloot of work to parse the urls and images in Github read as much as i can, and this results in the bug u described because Github does not really return the like with its relative url but rather just its name without full link, I'm in a bit of streaming to get this resolved in 1.0.5, please stay tuned for it.

**Comment by Dreamersoul** [comment]
Thanks for the response! Good luck!
