### ISSUE TITLE
Notification shows issue creation time as comment time

### ISSUE THREAD

**Issue by nyuszika7h** [k0shk0sh/FastHub#505]
**App Version: 2.1.0**

**OS Version: 25**

**Model: LGE-Nexus 5X**

 I got a notification about the "Bump." comment [here](https://github.com/notifico/notifico/issues/29), and for the time it said "142d", which is (I guess) when the issue was opened, rather than when the comment was made.

**Comment by k0shk0sh** [comment]
Unfortunately there is no way to know that except in the notification panel where I'm making extra requests to get the comment from the notification and display its time, in notifications tab screen I'm not doing that because it can be alot of requests at a time which will drain ur quota & slow down displaying. 
P.S: for notifications I'm limiting them to 10, so 10*10 api calls to give you exactly what is the comment and its time

**Comment by nyuszika7h** [comment]
Wait, I'm confused, what do you mean by notification panel/tab? Just to clarify, I'm talking about the notification shown in Android's notification bar or whatever it's called, not in-app.

**Comment by k0shk0sh** [comment]
First notification or the only notification appears in notification panel won't be having an api call :).
