### ISSUE TITLE
What's the point of pinned repos? 

### ISSUE THREAD

**Issue by smichel17** [k0shk0sh/FastHub#585]
At least in my usage, there's 100% overlap between how I would like to use pinned vs starred repos. The only difference is that pinned is local to my device (which makes it the less useful of the two).

What if instead of pinned repos, we just replaced the "Pinned" drawer shortcut with "Starred"?

**Comment by k0shk0sh** [comment]
The pinned tab is a much more elegant feature than starred repos, in pinned tabs you could lets say only have 5 repos that you regularly working either urs or your orgs repos, while starred repos could have thousands of records and will be hard to reach what you want for a daily collaborators job.

**Comment by smichel17** [comment]
I've always found the github home page's "Repositories you contribute to" list to do this pretty effectively. Is it available via API or website-only?

**Comment by k0shk0sh** [comment]
Nope they don't have, but that's not the problem five was a figure number :p they could be more, the repo could even just shared to collaborator to for ex: start reporting bugs, its more important for those who works in orgs, for me for instance since I removed FastHub from the drawer menu, best place is pinned :p 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
