### ISSUE TITLE
The scrolling bar keeps resizing

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#605]
**App Version: 3.0.0**

**OS Version: 25**

**Model: Samsung Galaxy S5**

When you're scrolling through an issue with a lot of comments like [this one,](https://github.com/k0shk0sh/FastHub/issues/567) the scrolling bar (or FastScroller, as you like to call it) keeps jumping around.  

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
Attaching a GIF
![2017-06-04_13-20-13](https://cloud.githubusercontent.com/assets/16872793/26763838/91d87020-4928-11e7-9b85-4219c60a1b98.gif)

**Comment by StanNL** [comment]
@yakov116 Yup that's what I meant

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well, I can't simply do anything about it, the issue has plenty of stuff in it that of course everytime you scroll the text will be rendered. I'm not really sure what do you expect from such case 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well, its became each comment has its own length plush the timeline has plenty of different rows, header, labels, comments. So it will definitely do that. Its what any fastscroller do. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
@k0shk0sh But couldn't you just calculate the sum of all the lengths of all the comments?

_Sent from my Samsung Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@StanNL for what reason exactly? as I said, when you have such complex multi-row list, you gonna have such thing.

**Comment by StanNL** [comment]
@k0shk0sh Well, I'm not a Java expert, nor an app developer at all, but I'd say it would look better if it was more consistent and it wouldn't be jumping from place to place all the time

_Sent from my Samsung Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
That would indeed be nice but hardly if even not possible to implement; the thing is the app uses a so-called _RecyclerView_ which is basically a box with scrollable content that is based on the same layout. Only the content that is actually visible to the user is also in the view hierarchy which means in this example comments that are not visible practically do not exist at all.
Because of that the RecyclerView, which only knows the total amount of comments and the height of the currently visible ones, has to assume all items have a similar height; it can't detect that there is for example one very big one in between because, as said, it doesn't exist as a view. The only way to detect the total height would be to add views for _all_ comments which is extremely expensive.
Theoretically there are also other ways to determine the height but all of them require very complex code or are also expensive so it's best to just leave it that way. Oh, and I think you can't even manually set the scrollbar position or dimensions from outside.

**Comment by k0shk0sh** [comment]
@wasdennnoch it is in 3.0.1 the fastscroller is fixed to one size so I hope everyone is happy

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
@k0shk0sh  Yeah that seems like a very reasonable solution to me

_Sent from my Samsung Galaxy S5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
@k0shk0sh I guess this doesn't change that it moves with different speeds but it's something.

**Comment by k0shk0sh** [comment]
@wasdennnoch  that's true and can't do anything about it for the meantime.

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
@wasdennnoch thanks ! I've been wondering why this happens on the Google Keep app for years...

_Sent from my Htc Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
