### ISSUE TITLE
Trending needs improvement

### ISSUE THREAD

**Issue by mabbamOG** [k0shk0sh/FastHub#611]
**App Version: 3.0.0**

**OS Version: 23**

**Model: OnePlus-ONE A2003**
(Its actually oneplus 2)

![this](http://i.imgur.com/osEdk1O.png) is the trending view filtered by weekly haskell. As you can see the bug is that items are repeated...also there are not that few items really trending.

Furthermore:
- search should be added to the languages like on the site
- also the view widgets are lacking some info, like the same you find when browsing someone's repositories

**Comment by k0shk0sh** [comment]
Well, simply we can't have these info because we are scraping GitHub trending page and getting data from it. So that point will not happen, looking at trending screen, the only thing is missing is built by, so can't really know what's more that you want.
Language list is there as well, not sure which one you referring to? Top languages are displayed in top of the list, the rest down sorted alphabetically, search language might be needed but it isn't in my list right now.

For the bug u found of duplicates I'll look into it later today

Thanks for reporting

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mabbamOG** [comment]
- trending info: the github webpage does show the language of the project. if you use trending without any language filter then it is unknown. even with a language filter, it does not hurt to keep it.

- language list: i had not noticed the language list being split as the separator is not visible. still it's a pretty long list to be looking for "Standard ML", and then "Scheme" so i think search should be implemented sooner or later anyway. Also having the language list along with the timespan is counterintuitive but that's another issue (think reddit).

It's worth to notice that these 2 points are actually more of a ux consistency issue than bugs...so it's very understandable they're not going to be implemented any time soon.
Thanks for the continued improvements!

**Comment by yakov116** [comment]
Would also be nice to be able to search that language list.
