### ISSUE TITLE
Reopen place


### ISSUE THREAD

**Issue by NiekertDev** [k0shk0sh/FastHub#614]
**App Version: 3.0.1**

**OS Version: 22**

**Model: HUAWEI-HUAWEI SCL-L21**

When you close the app and reopen it it launches the homescreen. Can you make it go back to the place you was?

_Sent from my HUAWEI SCL-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@NiekertDev Good Idea. I have asked @k0shk0sh in the past about this, I was told that at this we will not do this.
I will wait for his input on this.
Thanks for your feedback

**Comment by k0shk0sh** [comment]
Hey thanks for reporting this.

I don't think that this is how Mobile app behaves but I understand that it could be a problem to back to where you were that's why in next release there will a way to Pin almost anything to access it faster.
Thanks

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
