### ISSUE TITLE
Add "My repositories" item to navigation drawer.

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#625]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

Hey Kosh, can you please add a "my repositories" item to navigation drawer? I think is good to have it to quickly go directly to own repos, and will reduce the steps to get there.

Thanks

**Comment by k0shk0sh** [comment]
Hey @jahirfiquitiva , I hope you doing fine mate, thanks for the suggestion, wouldn't the Pin Repo would be better? like in terms of accessing things faster, so you could pin a repo and access even from app shortcut, do let me know what you think about this?

**Comment by yakov116** [comment]
@k0shk0sh I think when you add the ability to have multiple accounts you can add a drop down with all this.

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jahirfiquitiva** [comment]
@k0shk0sh 
Not really. The way I see things is:
- My repositories: the list of my very own repositories.
- Pinned: the list of repositories from other people that I am/will be interested in checking frequently.

I hope it makes sense. I think is easier for me, than having to pin all my own repos to quickly access to them.

**Comment by yakov116** [comment]
@jahirfiquitiva I agree with you

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Well that's not the case, 

Basically you pin Repos that you most frequently access and not the ones you interested on, if you are interested on a repo, Star / Fork it, these buttons they mean that you have interest on them, Pinned Repos, are the one that you frequently work on, like for example @yakov116  is tied to an Org and he has to do many support he also might like some other repos which then they will be listed in his `My Repos` so that means, that he might not find it quickly and instead he might need to filter or scroll his repos in order to reach it, I guess you misunderstand the whole idea behind star/forking & Pin. #247
