### ISSUE TITLE
Please add a better code viewer.

### ISSUE THREAD

**Issue by jahirfiquitiva** [k0shk0sh/FastHub#633]
---

 - FastHub Version: 3.0.1
 - Android Version: 7.0

Hey,

I would like to ask you to change the current code viewer.
I'm coming from Octodroid and I'm looking to switch completely to FastHub, which I download and test to see new stuff every now and then, until I think it's the perfect replacement.

Anyways, (besides the issues I already created/mentioned) there's this thing that annoys me the most of all of them: the code viewer.

See the differences:
![screenshot_20170608-223516](https://user-images.githubusercontent.com/10360816/26960263-6fe33cd6-4c9b-11e7-8644-ddff6ae9a293.png)
![screenshot_20170608-223549](https://user-images.githubusercontent.com/10360816/26960268-787cf3be-4c9b-11e7-8c4d-200ef6dc9952.png)

If you want me to mention them:
- In Octodroid one can zoom the code
- In Octodroid one can see the code in its original format
- In Octodroid lines are not split

Those are the things I can think of right now, but you could give it a try and find even more. I find those features really great in Octodroid.

Thanks in advance.

**Comment by k0shk0sh** [comment]
to be fair your compression is totally wrong, first of all, you enabled code wrap in FastHub which then will wrap the code to fit on screen width, second, you could just zoom in-out in FastHub as well as long as you don't wrap the code. 

you have the option to open in in browser if you want to see it in Github so i'm not really sure how this issue is even opened without proper testing?

**Comment by jahirfiquitiva** [comment]
Woops, sorry about this. It seems like I misunderstood what "Wrap code" option would do in the app.

Thanks for explanation.
