### ISSUE TITLE
Portrait mode doesn't wrap file contents correctly 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#676]
**App Version: 3.1.0**

**OS Version: 24**

**Model: Sony-E6653**

 here's a nice video of the issue https://www.dropbox.com/s/hxp242lyf7xh91h/ScreenRecord_2017-06-18-18-12-39.mp4?dl=0

Basically when you click wrap content checkbox in portrait mode it wraps the content, but at a slightly wider width than the screen,  by about 15%

No issues when do the same in landscape mode.

**Comment by yakov116** [comment]
@GeorgeWL Can you update to 3.2.0 and try again?

**Comment by GeorgeWL** [comment]
@yakov116 oooh, doesn't realise there was an update,  yeah I'll try shortly and see the difference

**Comment by k0shk0sh** [comment]
@GeorgeWL there will be no difference :p I guess I got it wrong, new highlight library used table to render code instead of pr that's why it isn't wrapped properly it's an easy fix but thanks for the headsup

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
