### ISSUE TITLE
[FR] Indicate in bell icon if you have notifications

### ISSUE THREAD

**Issue by wasdennnoch** [k0shk0sh/FastHub#714]
**App Version: 3.2.0**

**OS Version: 25**

**Model: samsung-GT-I9305**

Currently when you open the app the bell icon in the toolbar which takes you to the notifications always looks the same; it would be nice if it was filled out when there is a new notification.
(I have "real" notifications disabled but it seems the app already loads them on startup anyways so it could indicate in the icon if it found something).

**Comment by yakov116** [comment]
@wasdennnoch its there (I think so) but sometimes it works and sometimes not. Can't figure out when or why.
Maybe since you have them disabled it doesn't show

**Comment by wasdennnoch** [comment]
I enabled them yesterday when you replied to me and I got the notification but no icon indicator, so yeah, seems to be pretty inconsistent if it's already there.

**Comment by k0shk0sh** [comment]
@wasdennnoch it won't indicates that you notifications in real time since you already have indication in the notifications panel, however if you lets say you got notifications and u didn't mark them as read or open them, opening the app will highlight the icon. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
https://github.com/k0shk0sh/FastHub/blob/185b0d05b7b2469ce2790ae91f730b30757f3592/app/src/main/java/com/fastaccess/ui/modules/main/MainActivity.java#L91-L91

**Comment by wasdennnoch** [comment]
As I said it doesn't always seem to work; if I have notifications disabled it doesn't know if there are any in onInflateOptionsMenu. Ideally it should check for notifications in the background when I launch it and when that's finished show the result. I don't know if you're already doing that since I don't have time to look into the code right now, but it doesn't seem that way.

**Comment by k0shk0sh** [comment]
@wasdennnoch no api calls involved in this, simply it goes into the local db and check, besides you disabled the notifications so I bet nothing is being saved locally thats unread. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
It should so the API call when it gets launched then.

**Comment by wasdennnoch** [comment]
Btw I just got a notification (enabled the real ones) and it still didn't indicate that.

**Comment by k0shk0sh** [comment]
@wasdennnoch as I mentioned its not in real time, close & open app it will be highlighted. I don't see aby reason for it to call any api, since the notification panel is clearly good enough.

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
_But if xou have them disabled to save the battery of your crappy phone since the app can't use GMS I don't have any good notifications._

And where's the problem updating the icon as soon as it detects notifications?

Whatever.

**Comment by k0shk0sh** [comment]
@wasdennnoch first there is no way I can detect that there is a notification since I have no control over GitHub, second, even if let's say I made an api call when you open the app but a minute after you got a notification, still we will go to point zero which it will not show. You always can go to notifications to check, matter of fact you don't need too, since you will also receive an email indicating you have a notification from GitHub. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
@k0shk0sh Thanks, I didn't know about that. I thought there was a notification API.

> let's say I made an api call when you open the app but a minute after you got a notification, still we will go to point zero which it will not show

?
Does the API call automatically removes
the notification? I didn't quite understand that part.

**Comment by k0shk0sh** [comment]
Glad you got it :).


What I meant is, if you open the app and I made an api to retrieve notifications however there are no notification, but few seconds after, someone tag you in GitHub by right you should have a notification but then I wont know that until again you exit and renter the app. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
Yeah, that would indeed not be possible to catch, I was talkig about previously happened notifications. If there is no API how do you fetch them? Parsing the website?

It still doesn't seem to show the icon even if I got a notification but whatever, the email is a good point.

Just wondering, did you consider image uploading in-app to github ot imgur? If not I can open an issue for that.

**Comment by k0shk0sh** [comment]
@wasdennnoch there is a notification API but there is no push notifications,
Imgur? It exists in FastHub since three monts now :p

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@wasdennnoch 
![](http://i.imgur.com/0R9JlF5.png)

![](http://i.imgur.com/o1NCE4t.png)


_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wasdennnoch** [comment]
@k0shk0sh Wait, there is a select button? I never noticed that lol. Thanks for the hint ^^
