### ISSUE TITLE
Private Wiki Error

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#726]
- FastHub Version: 3.2.0
 - Android Version: 7.1.2
 - Phone Model: Google Pixel

If I go to the wiki of a private repo I get an error. Looking at the logs, it's a 404.

**Comment by k0shk0sh** [comment]
Please read the FAQ section in README.

**Comment by k0shk0sh** [comment]
And yes, the answer doesn't make sense at all :D . i'll edit it later after work to make it meaningful :D

**Comment by sm-g** [comment]
I really need to see wiki of my company's repository on my phone when commuting from/to office. Isn't it one of the main use cases?

Also if currently it is by design, why not disable wiki button? Or open wiki in webview?

**Comment by yakov116** [comment]
@sm-g since there is no api support for wiki 's (or for that matter there is barely any normal support for any github api) we are scrapping the data. For private wiki 's there is no way we can do that since we are not authorized (authenticated)
But opening in web view is an idea.... 

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
