### ISSUE TITLE
Some navigation improvements

### ISSUE THREAD

**Issue by dedepete** [k0shk0sh/FastHub#741]
**App Version: 3.2.0**  
**OS Version: 23**  
**Model: Yota Devices Limited-YD201**
___  
- [ ] The selected branch should be synchronized between Files and Commits tabs.  
_The thing that when I'm selecting branch in the Files tab I mean to see Commits for the selected one in another tab._  
- [x] The panel with branch selection should be placed at the top in the Files tab.  
_The navigation occurs through the branche's files, so the panel with branch selection has the priority than the simple navigation bar._

**Comment by k0shk0sh** [comment]
hey @dedepete , for the first - [ ]  I don't see it make sense, if you want to see commits when you selecting the files anyway? wouldn't selecting commits tab & changing the branch/tag would be more convenience since that made specifically for Commits? 
The branch selection has move intop.(y)

**Comment by dedepete** [comment]
@k0shk0sh, I meant that selecting tag/branch once for both tabs would be more convenience. For example, I have swithced to tag `3.0.0` in the Files tab and wanted to see commits for this branch, but when I'm switching to the Commits tab, the selected branch was not been updated and stayed at `master`.

**Comment by k0shk0sh** [comment]
@dedepete this selection doesn't mean for the whole repo otherwise I should have put it in somewhere where it changes everything. Commit does involves two API keys one for listing & one for counting so I'll be making three api calls upon switching the branch in either tab. Best way is to keep it as user choice rather than assuming that they want to do both at the same time. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
