### ISSUE TITLE
Scroll bar placement

### ISSUE THREAD

**Issue by eygraber** [k0shk0sh/FastHub#781]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

 When scrolling through an issue, the scroll bar doesn't always start at the top and end at the bottom. 

![Top](http://i.imgur.com/UNTPiNx.png)

![Bottom](http://i.imgur.com/f3l23C5.png)

**Comment by k0shk0sh** [comment]
Yep, i'm aware of that, had few complains about it being flickering even tho I can't do anything about it since I don't know the actual size of the row & that list has multiple types, so the argument end up on fixing the scroller size, plus I have added some top/bottom paddings to it to at least don't look ugly but tbh, its still ugly af and don't like it.

**Comment by k0shk0sh** [comment]
This has been fixed an matter of fact, I have added FastScroller for every screen in FastHub :)
