### ISSUE TITLE
Startup screen isn't themed

### ISSUE THREAD

**Issue by Thaodan** [k0shk0sh/FastHub#790]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: OnePlus
- BRAND: OnePlus  
- MODEL: ONEPLUS A3003  
---

 The start up screen isn't themed and still white.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JediBurrell** [comment]
This will not work properly.

The splash screen is there because the app is loading, while it is loading it doesn't know anything. It would have to first load what theme is, update itself, and by that time, it would already be loaded.

The only way to get this to work is a workaround, and it's a terrible workaround that causes lots of issues.

**Comment by rancidfrog** [comment]
Not sure I agree with comment.
Splash screen is there because it is told to be there.
On my device splash screen appears and disappears before we can even see it, leaving an annoying white flash before app loads.
Other project are able to fix this with a; simple change: https://github.com/GeoffreyMetais/vlc-android/commit/12a75955dc1e9e5c14d812e25ca3b7522c055bd1
I do not see your argument of terrible workaround with lots of issues.

**Comment by k0shk0sh** [comment]
@rancidfrog https://github.com/k0shk0sh/FastHub/issues/615 it is a terrible workaround & if it wasn't I wouldn't drop it. 

If it did work it would be there.
