### ISSUE TITLE
Nested lists are rendered differently than on GitHub

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#828]
I don't know wheter you want to follow GitHub closely or made it differently intentionally.
If the latter, just close the issue please.

```
1. a
   1. b
      1. c
         1. d
            1. e

- a
  - b
    - c
      - d
        - e
```

is rendered on GitHub as

![grafik](https://user-images.githubusercontent.com/325196/28760068-166d234c-75a4-11e7-9223-e552eb4c90be.png)

and on FastHub as

![grafik](https://user-images.githubusercontent.com/325196/28760144-a530dab0-75a4-11e7-9538-2df025b4b4e2.png)

So if you'd like to stay a bit more consistent with GitHub, ordered lists on the second level should be with lower roman numbers and on the third and deeper level with lower alphabet characters, unordered lists on the second level should be with empty circles and on the third and deeper level with filled squares.

This of course also should then work the same with mixed lists, so e. g.

```
1. a
   - b
     1. c

- a
  1. b
     - c
```

should be displayed as

![grafik](https://user-images.githubusercontent.com/325196/28760238-942aa876-75a5-11e7-80e2-d7fae117a13a.png)

**Comment by k0shk0sh** [comment]
Its not about staying close or far from GitHub, its about you understanding the limitation that Android has, things might look exactly the same in any `MD` file because they are rendered in an HTML which will behave exactly like in GitHub, but when displaying these stuff in `TextView` we are doing all the work to render these properly by HAND not CSS involved so it'll be impossible to do everything as in HTML.

**Comment by Vampire** [comment]
I understood already that it is hand-rendering. But this would not prevent you from using different list counter schemes for the lists, would it? As I said, it is also totally okay if you say you don't like to do it, but you like how it is, or that you say you don't want to make the effort to change it unless someone contributes it.

**Comment by k0shk0sh** [comment]
the whole problem with this isn't that I don't want to do, its because its almost impossible for me to know whether they are roman number, bullet or any other type 

https://github.com/k0shk0sh/FastHub/blob/9fca99c270dbf2268977adbcb27503ccd50e65d2/app/src/main/java/com/fastaccess/provider/timeline/handler/ListsHandler.java#L16-L16

**Comment by Vampire** [comment]
Hm, if I interpret this correctly from a quick look, you have rendered HTML and try to translate it to text and you have the DOM accessible. This class handles the `<li>` element and for getting the number you count the preceding `<li>` siblings and for ordered vs. non-ordered you check the parent about whether it is an `<ol>` or `<ul>`. But why not simply going recursively through the parents to check the nesting level? If a second `<ol>` or `<ul>` is found in the ancestors above the parent before you reach a node with `null` as parent, you are at second level, if you find another `<ol>` or `<ul>`, you can stop traversing as you are at third or deeper level. Then you could adjust the listing scheme accordingly.

Of course it could be again different from GitHub if they change their CSS, but at least it would be consistent now. And if they change, it can be adapted or not, just as you like.

Also, besides consistency, it has a reason they use different symbols for the different levels. You can more easily distinguish the levels of different entries. At least up to the third level, but deeper nesting gets ugly anyway. :-D
