### ISSUE TITLE
Table Support in the Markdown Editor

### ISSUE THREAD

**Issue by Vampire** [k0shk0sh/FastHub#840]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: samsung
- BRAND: samsung  
- MODEL: SM-G930F  
---

A button that helps with creating tables like e. g. the buttons for links or images would be great. It could ask for the amount of rows, or it could even allow you to enter your data in tabular form, generating the according Markdown afterwards.

As the Markdown table syntax is pretty limited in its possibilities, I think this should be doable with decent effort. 

It would even be more amazing if you could edit an existing table like that. E. g. by placing the caret in the table and pressing the table button.

**Comment by yakov116** [comment]
@Vampire you opened an issue already about this please keep all the issues together

**Comment by Vampire** [comment]
@yakov116 not that I'm aware of, what issue do you mean? If you mean the closed #804, then please read koshs comment. He asked me to create dedicated issues for the individual points.

**Comment by yakov116** [comment]
@Vampire You are correct. But the table was actually fixed in the debug build.

As for the table I explain in that issue that there is no way you an have table support.

**Comment by Vampire** [comment]
The table display is not part of this issue, just the table creation and editing. And after you said it is hardly possible, kosh said it is a great idea and asked me to create a separate issue for this. And as this is mainly koshs project as far as I understood, I did what _he_  told me.

**Comment by yakov116** [comment]
@Vampire Understood.
If you don't mind my explaining.

When there are many issues open what happens is that things get lost. Just for your info I have my own private repo with about 20 FastHub ideas.
The reason they are not here is that they are only idea's and they will one day get implemented.

I think that @k0shk0sh did not see how good you are at finding issues, so he said to make a new issue for each thing.

Since most of the issues you have found belong to the markdown. The best would be that they should be all i one. This way when we fix them all, we do them all at once
