### ISSUE TITLE
Can't view my private repositories

### ISSUE THREAD

**Issue by kylemart** [k0shk0sh/FastHub#867]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel XL  
---

When viewing a private repository I own, I'm getting a 'not found' error. 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@kylemart in the readme?

_Sent from my Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
Could you please elaborate? You are getting 404 for what exactly? You said you can't view yet you mentioned when viewing. So I'm abit confused.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GeorgeWL** [comment]
@k0shk0sh I'm not able to speak for them,  but my best guess is they intended to say 
> when attempting to view my private repositories

**Comment by k0shk0sh** [comment]
@GeorgeWL but he is viewing it 😕 so I guess the message is due to something in the repo that isn't there such as no files in the repo. I'll have to wait for his reply even tho I have plenty of closed issue to something related to it.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
