### ISSUE TITLE
Suggestion: Maybe a Skeleton view like Facebook / Alipay might be cool 

### ISSUE THREAD

**Issue by GeorgeWL** [k0shk0sh/FastHub#882]
**FastHub Version: 4.0.3**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Sony
- BRAND: Sony  
- MODEL: E6653  
---

 some examples :

https://github.com/ethanhua/Skeleton
https://github.com/elye/loaderviewlibrary

What do you think?

**Comment by k0shk0sh** [comment]
I have thought it and actually made a PR to a similar library so I could use it in FastHub, but was throwing away with other things that kept me busy of it.  

Not so sure what value does this adds honestly but my idea was to use it in  (PR, Issue, Commit & Repo Screen) since I know ProgressDialog is depecrated. 

the meantime I have no interest to do this and if anyone wants to PR it that'd be great.

**Comment by GeorgeWL** [comment]
@k0shk0sh well I know Facebook etc use it as a way to make loading over slow connection feel more smooth. 

But effectively doing the Skeleton until all the assets load properly, then when they're in carrying on like usual
