### ISSUE TITLE
[Enterprise] Profile pictures are not being loaded

### ISSUE THREAD

**Issue by Zeeker** [k0shk0sh/FastHub#905]
**FastHub Version: 4.1.0**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** LG G5  
---

As the title suggests, when I log in via my enterprise account (using an OAuth token generated for the app) I'm unable to see any profile pictures. The space where the pictures would appear are simply empty.

I've tried to fix the issue by clearing the app cache but this didn't lead to an improvement.

**Comment by k0shk0sh** [comment]
it won't be fixed as GitHub needs to change something in their api, currently they aren't accepting any headers to determine that its u for images and that's why it fails, I have reported this to GitHub two months ago and they said they can't promise me to get it fixed but they will try which will never happen

**Comment by k0shk0sh** [comment]
![](https://i.imgur.com/hwRLLFo.png)

**Comment by Zeeker** [comment]
Well, thanks for the feedback anyway.
