### ISSUE TITLE
Nav drawer not needed

### ISSUE THREAD

**Issue by HeinrichReimer** [k0shk0sh/FastHub#91]
The navigation drawer is not really necessary for the app.
The feedback and settings options should go in the overflow menu and the GitHub link, app version and ad toggle should go on a separate "about" page where you could also list some of your social profiles.

**Comment by k0shk0sh** [comment]
It'll be very soon helpful as I'm planning to change some navigation design, such as instead of having profile & gists, we gonna have Issues & Pull Requests, so the before are going to be in Menu Drawer as well as going to have trending and some useful stuff. If I just have a week off, I would wrap it up lol.

**Comment by HeinrichReimer** [comment]
Totally legit

**Comment by Rainer-Lang** [comment]
As NavDrawer I suggest: https://github.com/mikepenz/MaterialDrawer 
You're really flexible with this.

**Comment by HeinrichReimer** [comment]
@mikepenz' library indeed is very flexible. If you need something a bit simpler you could also check out my [material-drawer](https://github.com/HeinrichReimer/material-drawer) library.

**Comment by k0shk0sh** [comment]
closing this issue as it doesn't need to be open, i'm trying to finalize the opened issues before later night or tomorrow release.
