### ISSUE TITLE
Use Transparent theme for launch to match user choice

### ISSUE THREAD

**Issue by rancidfrog** [k0shk0sh/FastHub#936]
**FastHub Version: 4.1.0**  
**Android Version: 7.1.1 (SDK: 25)**  
**Device Information:**  
- **Manufacturer:** OnePlus  
- **Brand:** OnePlus  
- **Model:** OnePlus5  
---

 Currently when app is launched there is a white screen showing for a second before app is ready,
even when dark theme is being used.

VLC solved this with following commit, maybe it can help:  [Transparent theme for smoother startup](https://github.com/GeoffreyMetais/vlc-android/commit/12a75955dc1e9e5c14d812e25ca3b7522c055bd1)

**Comment by yakov116** [comment]
#902 #790 and many more

**Comment by rancidfrog** [comment]
#790 Yes, that is the same issue.
But, why the Won't Fix status.
Just because one dev could not find a possible solution that does not mean there is no solution.
VLC is a big project and I linked with their solution for annoying white background appearing on launch regardless of selected theme.
It would be great to know that you are actually looking at how other devs tackle similar problems, especially when other project are established.
The comment given for not fixing it is, "The only way to get this to work is a workaround, and it's a terrible workaround that causes lots of issues", which is not true.
VLC works fine, and there are no issues regarding their fix.

**Comment by k0shk0sh** [comment]
apparently you don't know the fix that we are talking about.  so I'm not gonna comment on this. 
to comment on your so well established projects their solution is to make the background transparent which I don't see as a solution but rather a lazy way of saying I'm not going bother about it. 

I'm really not gonna go into an argument that isn't going to take us any where. 
it is marked as wont fix because it can't be fixed the way we want it to fixed with multiple themes. 
so having the white background and fasthub logo on it describe its theme & identity.

**Comment by yakov116** [comment]
@rancidfrog "The maker knows the its product best"

If one dev found a solution that is because works for them. Another project it may not work at all.

Had this been the first time the issue was raised i would hear your comment. This issue has been brought up over 4 times. You didn't even search before you opened a new issue. 

Feedback is always appreciated and is the only way we can succeed. Yet there is no need for criticizing at all

**Comment by rancidfrog** [comment]
Why not provide at least a setting to disable Splash. As app is loaded immediately, in my case splash screen is only flashing quickly. App spends more time in this state:

￼

**Comment by yakov116** [comment]
@rancidfrog At that point we are doing a few check such as making sure google play services is enabled and checking if the user is pro. There is no way to disable that.

**Comment by yakov116** [comment]
> Why not provide at least a setting to disable Splash. As app is loaded immediately, in my case splash screen is only flashing quickly.

@Raffaele74 If its only quickly then why should we go at great length to disable it?

> App spends more time in this state

Well that is github's issue we cant control the speed of the api

**Comment by rancidfrog** [comment]
I do not understand, play services?
I mean having a switch in settings to enable or disable splash screen, because it is useless: App does not spend time in splash screen, so there is not even time to read what appears. It is less than half a second transition, which makes it annoying as all it does is flash white screen and then transitions immediately to app. 

Anyway it is your choice, I just wanted to inform you of another solution.
But as k0sh said, "rather a lazy way of saying I'm not going bother about it."

Which applies more to you, since users have already mentioned issue several times but you rather do nothing.
One solution would be to disable splash, which should not appear since app loads immediately so there is no time for splash.
Or, there is a workaround that causes no real issues, which you can revert when you find a better way.

Again, this is your project.
Me, I rather have a "rather a lazy way of saying I'm not going bother about it." 
Since it means that there is np flashing white screen when app loads.

**Comment by rancidfrog** [comment]
When switching from markup editor to preview and back, sometime [obj] appear instead of text:

![](https://i.imgur.com/6RwoTCO.png)

**Comment by yakov116** [comment]
@rancidfrog open a new issue for that please

**Comment by yakov116** [comment]
>I do not understand, play services?
I mean having a switch in settings to enable or disable splash screen, because it is useless: App does not spend time in splash screen, so there is not even time to read what appears. It is less than half a second transition, which makes it annoying as all it does is flash white screen and then transitions immediately to app.

As I have said before we are doing checks at that point. If you would just search the issues for "google" (not even with the word "services") you would see what I am talking about.

Thanks for all your feedback

**Comment by k0shk0sh** [comment]
@yakov116 it's a fundamental Android thing to have the splash screen, so if the OP is okay with the 99.99% of Android apps having it but having an issue with fasthub displaying it then that's a different issue. 

so please lets keep this tidy. 

i marked it with duplicate & wont fix that really means its a dead end and should we put no length on discussing it.

**Comment by rancidfrog** [comment]
Another option, would be to use another colour, maybe similar to your logo blues:
For example, neutrinote also uses quick splash screen but in blue: https://play.google.com/store/apps/details?id=com.appmindlab.nano&hl=en
Another app that has greenish Splash is Magisk.

Fundemental Android?
Chrome does not have a splash and it is google, neither does google calendar. 
Normally I do not use google apps nor google play store, so would not know.
But, k9mail, browser apps, twidere, open camera, Instagram, whatsapp, vanills music, aimp, foobar, ...
All do not have splash screen.
Also you are probably following google guidelines.
But you do realize that not even google follow their own rules.
You use something when it is needed.

**Comment by yakov116** [comment]
@rancidfrog Enough... We explain our side no need to go farther anymore

Locking conversation
