### ISSUE TITLE
True AMOLED black theme.

### ISSUE THREAD

**Issue by krompus** [k0shk0sh/FastHub#949]
**FastHub Version: 4.2.0**  
**Android Version: 8.0.0 (SDK: 26)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel  
---

Love FastHub; best Android Github app by far. I purchased premium for the themes, but I'd really appreciate a true AMOLED black theme; the dark purple highlights clash with my system-wide black theme.

**Comment by k0shk0sh** [comment]
@krompus there is an amlod theme that is literally black that you can't see anything such as elevation :D . so i'm really confused on whether you have tried the themes or not :D

**Comment by krompus** [comment]
@k0shk0sh Inhave the AMOLED theme applied, but there are (very) dark purple backgrounds for highlights throughout.

https://i.imgur.com/EebNz1y.png

I'd like to do away with the purple if possible. :)

**Comment by krompus** [comment]
@k0shk0sh Inhave the AMOLED theme applied, but there are (very) dark purple backgrounds for highlights throughout.

https://i.imgur.com/EebNz1y.png

I'd like to do away with the purple if possible. :)

**Comment by k0shk0sh** [comment]
@krompus unfortunately that's not possible buddy, if I had put these cards as the background color then it will be really really hard to distinguish the comments from other views. 

I tried to make them as dark as possible tho :). 

You could imagine it being as the background, first use any other theme, reopen the issue you linked or this one look at the comments & you will see that the comments row must have background color that is different from the app background. its by design to ease things for the user & make it easier for them to get their eyes on that specific place of the screen. 

I hope that explains everything :) .. 

Thanks for your support btw

**Comment by k0shk0sh** [comment]
@krompus btw you could upload images from FastHub to post them here :) use the markdown image icon and then select to upload image from your sdcard :) FastHub will take care of the rest once u select the image.

**Comment by krompus** [comment]
Ah, no worries, then.

**Comment by krompus** [comment]
@k0shk0sh![Noice](https://i.imgur.com/pKOWVRS.jpg)

**Comment by k0shk0sh** [comment]
Loool :D . glad you could find it that quick :p . the other fun part is, you could also post gifs :p

**Comment by krompus** [comment]
@k0shk0sh Oh neat! I tried using the same selector, but it won't let me upload .mp4; perhaps it only supports actual .gif?

**Comment by shgaurav** [comment]
https://media.giphy.com/media/iqfYgtx8oWw4o/giphy.gif

**Comment by shgaurav** [comment]
![Lol](https://media.giphy.com/media/iqfYgtx8oWw4o/giphy.gif)

**Comment by shgaurav** [comment]
Did it haha
